grafana:
  enabled: true
  service:
    type: LoadBalancer
  nodeSelector:
    role: monitoring
  image:
    tag: "10.2.0"
  adminPassword: password
  env:
    GF_FEATURE_TOGGLES_ENABLE: "lokiQueryBuilder"
    GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/default/playwright.json
  persistence:
    enabled: false
  defaultDashboardsEnabled: false
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.monitoring.svc.cluster.local:3100
          isDefault: true
          jsonData:
            maxLines: 1000
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      playwright:
        json: |
          {
            "id": null,
            "title": "Playwright TTL",
            "timezone": "browser",
            "schemaVersion": 36,
            "version": 1,
            "refresh": "10s",
            "time": {
              "from": "now-1h",
              "to": "now"
            },
            "panels": [
              {
                "type": "timeseries",
                "title": "Avg TTL (1m) HTTP 200",
                "targets": [
                  {
                    "expr": "avg_over_time({pod=~\"playwright-.*\"} | json | __error__=\"\" | message=\"Page load metrics\" | status=\"200\" | unwrap loadTime [1m]) by (url)",
                    "refId": "A",
                    "datasource": {
                      "type": "loki",
                      "uid": "loki"
                    }
                  }
                ],
                "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 }
              },
              {
                "type": "timeseries",
                "title": "Count of non-200 HTTP",
                "targets": [
                  {
                    "expr": "sum by (url)(count_over_time({pod=~\"playwright-.*\"} | json |  __error__=\"\" | message=\"Page load metrics\" | status!=\"200\" | label_format status=\"{{.status}}\" [1m]))",
                    "refId": "A",
                    "datasource": {
                      "type": "loki",
                      "uid": "loki"
                    }
                  }
                ],
                "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 }
              }
            ]
          }

promtail:
  config:
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  enabled: true

loki:
  image:
    tag: "2.9.3"
  enabled: true
  persistence:
    enabled: false
  service:
    type: ClusterIP
  labels:
    app: loki
    app.kubernetes.io/name: loki
  podLabels:
    app: loki
    app.kubernetes.io/name: loki