apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-load-tester
  labels:
    app: playwright-load-tester
    app.kubernetes.io/name: playwright-load-tester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playwright-load-tester
  template:
    metadata:
      labels:
        app: playwright-load-tester
        app.kubernetes.io/name: playwright-load-tester
    spec:
      nodeSelector:
        role: playwright
      containers:
        - name: playwright-load-tester
          image: 209479288335.dkr.ecr.eu-north-1.amazonaws.com/playwright-load-tester:latest
          imagePullPolicy: Always
          env:
            - name: TARGET_URL
              value: "https://example.ru"  # Replace with the actual target
            - name: CONCURRENT_SESSIONS
              value: "3"
            - name: TEST_DURATION
              value: "300000"
            - name: THINK_TIME
              value: "1000"
          ports:
            - containerPort: 3000
          resources:
              requests:
                cpu: "1000m"    # 1 full vCPU
                memory: "1Gi"
              limits:
                cpu: "2"
                memory: "2Gi"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: playwright-load-tester
spec:
  selector:
    app: playwright-load-tester
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
